import React from 'react'
import './Background.scss';
import Marquee from 'react-fast-marquee';
import White from './components/White';
import Yellow from './components/Yellow';

const Background = () => {
  return (
    <>
      <div className="background">
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>
        <White></White>
        <Yellow></Yellow>

      </div>
    </>
  )
}

export default Background